spring:
  application:
    name: dingdong

  datasource:
    url: jdbc:postgresql://localhost:5432/dingdong
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: ture

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ENC(xGpMf3tCPdzlqie6n0qyn6PV2SNH11BlDmK3hn4R2VpqoygYDLQMDqQHCcwlLnFjm2UBI9krWBM=)
  access-token-expiration: 900000 # 15분
  refresh-token-expiration: 1209600000 # 14일

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
